spring:
  profiles:
    active: "dev"

my:
  VALID_BANKNOTES:
    - 1
    - 10
    - 100
    - 1000
    - 5
    - 50
    - 500
    - 5000

---

spring:
  profiles: prod

---

spring:
  profiles: test

---

spring:
  profiles: dev
  main:
    banner-mode: "off"

logging:
  level:
    .: error
    org.springframework: ERROR
    com.belorechev: ERROR